Repository Ciela-Institute/caustics, pull requests merged in 2023-12, with the labels that each got.

#105 fix white logo to look better
  .pre-commit-config.yaml
  media/caustics_logo.png
  media/caustics_logo_white.png
Labels: documentation

#111 Adding gaussian quadrature integrator
  src/caustics/sims/lens_source.py
  src/caustics/utils.py
  tests/test_simulator.py
Labels: enhancement

#121 docs: Attempt to add light/dark logo for website
  docs/source/_config.yml
  docs/source/intro.md
Labels: docs

#120 ci: dependabot now commits updates to dev branch
  .github/dependabot.yml
Labels: ci

#128 ci: Add matplotlib import in RTD pre_build
  .readthedocs.yml
Labels: docs, ci

#122 style: Mark equations where black formatting should not apply
  src/caustics/constants.py
  src/caustics/cosmology.py
  src/caustics/lenses/base.py
  src/caustics/lenses/epl.py
  src/caustics/lenses/mass_sheet.py
  src/caustics/lenses/multiplane.py
  src/caustics/lenses/nfw.py
  src/caustics/lenses/pixelated_convergence.py
  src/caustics/lenses/pseudo_jaffe.py
  src/caustics/lenses/sie.py
  src/caustics/lenses/tnfw.py
  src/caustics/lenses/utils.py
  src/caustics/light/sersic.py
  src/caustics/utils.py
  tests/test_kappa_grid.py
Labels: style

#127 docs: Update tutorials to call modules with new paths
  docs/source/tutorials/BasicIntroduction.ipynb
  docs/source/tutorials/InvertLensEquation.ipynb
  docs/source/tutorials/LensZoo.ipynb
  docs/source/tutorials/MultiplaneDemo.ipynb
  docs/source/tutorials/Playground.ipynb
  docs/source/tutorials/Simulators.ipynb
  docs/source/tutorials/VisualizeCaustics.ipynb
Labels: bug, docs

#137 chore: add pre-commit badge
  README.md
Labels: docs, chore

#131 feat: timedelay for multiplane lensing
  docs/source/tutorials/InvertLensEquation.ipynb
  docs/source/tutorials/MultiplaneDemo.ipynb
  docs/source/tutorials/VisualizeCaustics.ipynb
  src/caustics/lenses/base.py
  src/caustics/lenses/multiplane.py
  tests/test_multiplane.py
  tests/test_sie.py
Labels: feat
