Repository Ciela-Institute/caustics, pull requests merged in 2023-05, with the labels that each got.

#33 Packed
  .github/workflows/python-app.yml
  pyproject.toml
  requirements.txt
  src/caustic/lenses/kappa_grid.py
  src/caustic/lenses/utils.py
  src/caustic/packed.py
  src/caustic/parametrized.py
  src/caustic/sources/pixelated.py
  src/caustic/utils.py
  test/test_interpolate_image.py
  test/test_kappa_grid.py
  test/test_sersic.py
  test/utils.py
Labels: refactor, user experience

#36 Update Kappa Grid fft and dtype behavior
  .github/workflows/coverage.yaml
  .github/workflows/python-app.yml
  README.md
  pyproject.toml
  requirements.txt
  src/caustic/cosmology.py
  src/caustic/lenses/kappa_grid.py
  src/caustic/utils.py
Labels: bug, documentation

#38 Adding documentation to all classes and methods in google style
  src/caustic/cosmology.py
  src/caustic/fwd_raytrace.py
  src/caustic/lenses/base.py
  src/caustic/lenses/epl.py
  src/caustic/lenses/external_shear.py
  src/caustic/lenses/multiplane.py
  src/caustic/lenses/nfw.py
  src/caustic/lenses/point.py
  src/caustic/lenses/pseudo_jaffe.py
  src/caustic/lenses/sie.py
  src/caustic/lenses/singleplane.py
  src/caustic/lenses/sis.py
  src/caustic/lenses/utils.py
  src/caustic/parameter.py
  src/caustic/parametrized.py
  src/caustic/sources/base.py
  src/caustic/sources/pixelated.py
  src/caustic/sources/sersic.py
  src/caustic/utils.py
Labels: documentation

#37 Simulator class
  src/caustic/lenses/base.py
  src/caustic/lenses/utils.py
  src/caustic/packed.py
  src/caustic/parametrized.py
  src/caustic/simulator.py
Labels: enhancement
