Repository Ciela-Institute/caustics, pull requests merged in 2023-07, with the labels that each got.

#52 Parameterized name update
  caustic/cosmology.py
  caustic/lenses/base.py
  caustic/lenses/epl.py
  caustic/lenses/external_shear.py
  caustic/lenses/multiplane.py
  caustic/lenses/nfw.py
  caustic/lenses/pixelated_convergence.py
  caustic/lenses/point.py
  caustic/lenses/pseudo_jaffe.py
  caustic/lenses/sie.py
  caustic/lenses/singleplane.py
  caustic/lenses/sis.py
  caustic/namespace_dict.py
  caustic/parameter.py
  caustic/parametrized.py
  caustic/sources/pixelated.py
  caustic/sources/sersic.py
  test/test_cosmology.py
  test/test_epl.py
  test/test_external_shear.py
  test/test_kappa_grid.py
  test/test_multiplane.py
  test/test_namespace_dict.py
  test/test_nfw.py
  test/test_parameter.py
  test/test_parametrized.py
  test/test_point.py
  test/test_pseudo_jaffe.py
  test/test_sersic.py
  test/test_sie.py
  test/test_sis.py
Labels: enhancement, refactor

#57 refactoring for unpack decorator
  caustic/cosmology.py
  caustic/lenses/epl.py
  caustic/lenses/external_shear.py
  caustic/lenses/multiplane.py
  caustic/lenses/nfw.py
  caustic/lenses/pixelated_convergence.py
  caustic/lenses/point.py
  caustic/lenses/pseudo_jaffe.py
  caustic/lenses/sie.py
  caustic/lenses/singleplane.py
  caustic/lenses/sis.py
  caustic/parametrized.py
  caustic/sources/pixelated.py
  caustic/sources/sersic.py
  caustic/utils.py
  test/test_parametrized.py
  test/test_pseudo_jaffe.py
  test/test_sersic.py
  test/utils.py
Labels: refactor, user experience

#58 n_dynamic, n_static, and dynamic_size are now updated live
  caustic/parametrized.py
Labels: bug
