Repository Ciela-Institute/caustics, pull requests merged in 2023-10, with the labels that each got.

#84 Bug fixes 20231008
  .github/workflows/coverage.yaml
  .github/workflows/python-app.yml
  caustic/cosmology.py
  caustic/lenses/base.py
  caustic/parameter.py
  caustic/parametrized.py
  requirements.txt
  setup.py
  test/test_cosmology.py
  test/test_multiplane.py
  test/test_parameter.py
Labels: bug

#86 config jupyter notebook tutorials in website
  .github/workflows/documentation.yaml
  docs/conf.py
  docs/index.rst
  docs/pull_notebooks.py
  docs/tutorials.rst
Labels: documentation

#88 Filling out the basic simulator
  caustic/__init__.py
  caustic/forward_raytrace.py
  caustic/lenses/__init__.py
  caustic/lenses/base.py
  caustic/parameter.py
  caustic/sims/__init__.py
  caustic/sims/lens_source.py
  caustic/sims/simulator.py
  caustic/utils.py
  test/test_parameter.py
  test/test_parametrized.py
  test/test_simulator.py
  test/utils.py
Labels: enhancement
