Repository Ciela-Institute/caustics, pull requests merged in 2024-07, with the labels that each got.

#228 ci: fix codecov token
  .github/workflows/ci.yml
  src/caustics/__init__.py
  src/caustics/data/__init__.py
  src/caustics/data/hdf5dataset.py
  src/caustics/data/illustris_kappa.py
  src/caustics/data/probes.py
  src/caustics/light/__init__.py
  src/caustics/light/probes.py
Labels: ci

#233 Add gui install instructions to websim.rst
  docs/source/websim.rst
Labels: docs

#245 refactor: move quad_level to init
  docs/source/examples/Example_ImageFit_LM.ipynb
  docs/source/examples/Example_ImageFit_NUTS.ipynb
  docs/source/intro.md
  docs/source/tutorials/InterfaceIntroduction_oop.ipynb
  docs/source/tutorials/InterfaceIntroduction_yaml.ipynb
  docs/source/tutorials/example.yml
  src/caustics/sims/lens_source.py
  tests/models/test_mod_api.py
  tests/test_simulator_runs.py
Labels: refactor
