Repository Ciela-Institute/caustics, pull requests merged in 2025-01, with the labels that each got.

#307 tests: Time delay now tested for SIE
  src/caustics/lenses/base.py
  tests/test_sie.py
  tests/test_time_delay.py
Labels: fix, tests

#302 refactor: normalize variable names across caustics objects
  README.md
  docs/source/examples/Example_ImageFit_LM.ipynb
  docs/source/examples/Example_ImageFit_MCMC.ipynb
  docs/source/examples/Example_QSOLensFit.ipynb
  docs/source/gravlensingintro.ipynb
  docs/source/intro.md
  docs/source/tutorials/InterfaceIntroduction_func.ipynb
  docs/source/tutorials/InterfaceIntroduction_oop.ipynb
  docs/source/tutorials/InterfaceIntroduction_yaml.ipynb
  docs/source/tutorials/Introduction.ipynb
  docs/source/tutorials/InvertLensEquation.ipynb
  docs/source/tutorials/LensZoo.ipynb
  docs/source/tutorials/Microlensing.ipynb
  docs/source/tutorials/MultiplaneDemo.ipynb
  docs/source/tutorials/VisualizeCaustics.ipynb
  src/caustics/lenses/epl.py
  src/caustics/lenses/func/epl.py
  src/caustics/lenses/func/nfw.py
  src/caustics/lenses/func/point.py
  src/caustics/lenses/func/pseudo_jaffe.py
  src/caustics/lenses/func/sie.py
  src/caustics/lenses/func/sis.py
  src/caustics/lenses/func/tnfw.py
  src/caustics/lenses/nfw.py
  src/caustics/lenses/point.py
  src/caustics/lenses/pseudo_jaffe.py
  src/caustics/lenses/sie.py
  src/caustics/lenses/sis.py
  src/caustics/lenses/tnfw.py
  src/caustics/tests.py
  tests/test_base.py
  tests/test_epl.py
  tests/test_nfw.py
  tests/test_point.py
  tests/test_sie.py
  tests/test_simulator_runs.py
  tests/test_sis.py
  tests/test_time_delay.py
Labels: refactor

#305 refactor: Change z_s from argument to caskade param
  README.md
  docs/source/_toc.yml
  docs/source/examples/Example_ImageFit_LM.ipynb
  docs/source/examples/Example_ImageFit_MCMC.ipynb
  docs/source/examples/Example_QSOLensFit.ipynb
  docs/source/gravlensingintro.ipynb
  docs/source/intro.md
  docs/source/tutorials/Introduction.ipynb
  docs/source/tutorials/InvertLensEquation.ipynb
  docs/source/tutorials/LensZoo.ipynb
  docs/source/tutorials/Microlensing.ipynb
  docs/source/tutorials/MultiSource.ipynb
  docs/source/tutorials/MultiplaneDemo.ipynb
  docs/source/tutorials/VisualizeCaustics.ipynb
  src/caustics/lenses/base.py
  src/caustics/lenses/batchedplane.py
  src/caustics/lenses/enclosed_mass.py
  src/caustics/lenses/epl.py
  src/caustics/lenses/external_shear.py
  src/caustics/lenses/mass_sheet.py
  src/caustics/lenses/multiplane.py
  src/caustics/lenses/multipole.py
  src/caustics/lenses/nfw.py
  src/caustics/lenses/pixelated_convergence.py
  src/caustics/lenses/pixelated_potential.py
  src/caustics/lenses/point.py
  src/caustics/lenses/pseudo_jaffe.py
  src/caustics/lenses/sie.py
  src/caustics/lenses/singleplane.py
  src/caustics/lenses/sis.py
  src/caustics/lenses/tnfw.py
  src/caustics/lenses/utils.py
  src/caustics/light/base.py
  src/caustics/sims/lens_source.py
  src/caustics/sims/microlens.py
  src/caustics/tests.py
  tests/test_base.py
  tests/test_batchedplane.py
  tests/test_enclosed_mass.py
  tests/test_epl.py
  tests/test_external_shear.py
  tests/test_jacobian_lens_equation.py
  tests/test_kappa_grid.py
  tests/test_lens_potential.py
  tests/test_masssheet.py
  tests/test_multiplane.py
  tests/test_multipole.py
  tests/test_nfw.py
  tests/test_point.py
  tests/test_pseudo_jaffe.py
  tests/test_sie.py
  tests/test_simulator_runs.py
  tests/test_singleplane.py
  tests/test_sis.py
  tests/test_time_delay.py
  tests/test_tnfw.py
  tests/utils/__init__.py
Labels: refactor

#315 fix: ensure the forward raytrace points are unique
  src/caustics/lenses/func/base.py
Labels: fix

#306 refactor: better use of autograd for base lens quantities
  src/caustics/func.py
  src/caustics/lenses/base.py
  src/caustics/lenses/enclosed_mass.py
  src/caustics/lenses/func/__init__.py
  src/caustics/lenses/func/nfw.py
  src/caustics/lenses/func/tnfw.py
  src/caustics/lenses/nfw.py
  src/caustics/lenses/tnfw.py
  tests/test_lens_potential.py
  tests/test_nfw.py
  tests/test_tnfw.py
  tests/utils/__init__.py
Labels: refactor

#301 fix: handle q=1 for sie
  src/caustics/lenses/func/sie.py
  src/caustics/tests.py
  tests/test_sie.py
Labels: fix

#304 feat: New parametrizations for external shear and point mass
  docs/source/tutorials/MultiSource.ipynb
  src/caustics/func.py
  src/caustics/lenses/external_shear.py
  src/caustics/lenses/func/__init__.py
  src/caustics/lenses/func/external_shear.py
  src/caustics/lenses/func/sie.py
  src/caustics/lenses/point.py
  src/caustics/lenses/sie.py
  tests/test_external_shear.py
  tests/test_point.py
  tests/test_sie.py
Labels: feat

#317 docs: update docstrings remove z_s and params
  src/caustics/cosmology/FlatLambdaCDM.py
  src/caustics/cosmology/base.py
  src/caustics/lenses/base.py
  src/caustics/lenses/func/enclosed_mass.py
  src/caustics/lenses/func/multipole.py
  src/caustics/lenses/multiplane.py
  src/caustics/lenses/multipole.py
  src/caustics/lenses/pixelated_convergence.py
  src/caustics/lenses/pseudo_jaffe.py
  src/caustics/lenses/singleplane.py
  src/caustics/lenses/tnfw.py
  src/caustics/light/light_stack.py
  src/caustics/light/pixelated.py
  src/caustics/light/pixelated_time.py
  src/caustics/light/sersic.py
  src/caustics/light/star_source.py
  src/caustics/sims/lens_source.py
  src/caustics/sims/microlens.py
Labels: docs

#313 Basic simulator tutorial
  docs/source/_config.yml
  docs/source/_toc.yml
  docs/source/intro.md
  docs/source/tutorials/BasicCustomSimulator.ipynb
  docs/source/tutorials/IntroductionInDepth.ipynb
Labels: docs
